name: Semantic Pull Request

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  main:
    name: Validate Pull Request title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
          requireScope: true
          scopePattern: "^[a-z]+$"
          subjectPattern: '^[a-z0-9\s\-\_.,!]+$'
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            must contain only lowercase letters, numbers, spaces, and allowed punctuation ( - _ . , ! ).
          ignoreLabels: |
            bot

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
